#!/usr/bin/env bash
# This script displays lines containing the word "bash" and extracts the PID

# Use the ps command with grep to filter lines containing "bash"
# shellcheck disable=SC2009
ps aux | grep bash | grep -v grep
