#!/usr/bin/env bash
# This script stops the 7-highlander process

# Find the PID of the 7-highlander process
process_pid=$(pgrep -f "7-highlander")

# Check if the process is running
if [ -n "$process_pid" ]; then
    # Use kill to send a SIGTERM signal to the process
    kill -TERM "$process_pid"
    echo "Terminated"
else
    echo "Process not found"
fi
