#!/usr/bin/env bash
# Displays all acive IPv4 addresses on the machine.

sudo sed -i 's/^127\.0\.0\.1.*localhost$/127.0.0.2 localhost/' /etc/hosts
sudo sed -i 's/^.*facebook.com.*$/8.8.8.8 facebook.com/' /etc/hosts
